# Generated by Django 4.2.7 on 2026-07-06 22:13

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_projects_group_i_a0275d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to=api.models.file_upload_path)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='storage_tier',
            field=models.CharField(choices=[('100MB', '100 Mo'), ('500MB', '500 Mo'), ('1GB', '1 Go'), ('5GB', '5 Go'), ('10GB', '10 Go'), ('50GB', '50 Go'), ('100GB', '100 Go'), ('unlimited', 'Illimité')], default='1GB', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StorageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('warning_80', 'Avertissement 80%'), ('warning_90', 'Avertissement 90%'), ('quota_reached', 'Quota atteint')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_notifications', to='api.company')),
            ],
            options={
                'verbose_name': 'Notification de stockage',
                'verbose_name_plural': 'Notifications de stockage',
                'db_table': 'storage_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_shares_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='api.companygroup')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de fichier',
                'verbose_name_plural': 'Partages de fichiers',
                'db_table': 'file_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.company'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['company', 'uploaded_by'], name='files_company_9179a2_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['mime_type'], name='files_mime_ty_5c3514_idx'),
        ),
    ]
