# Generated by Django 4.2.7 on 2026-07-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_file_company_storage_tier_company_storage_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Tâche assignée'), ('task_completed', 'Tâche terminée'), ('task_delayed', 'Tâche en retard'), ('comment_added', 'Commentaire ajouté'), ('member_added', 'Membre ajouté'), ('milestone_due', 'Jalon à échéance'), ('meeting_reminder', 'Rappel de réunion'), ('meeting_processing', 'Traitement de réunion en cours'), ('meeting_processed', "Réunion traitée par l'IA"), ('report_processing', 'Génération de rapport en cours'), ('report_ready', 'Rapport de projet prêt'), ('task_failed', "Échec d'une tâche en arrière-plan")], max_length=30),
        ),
    ]
