# Generated by Django 4.2.7 on 2026-07-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meeting_reminder_sent_at_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_audit_logs',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_key', models.CharField(max_length=40)),
                ('event_type', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_metrics',
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_outbox',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Tâche assignée'), ('task_completed', 'Tâche terminée'), ('task_delayed', 'Tâche en retard'), ('comment_added', 'Commentaire ajouté'), ('member_added', 'Membre ajouté'), ('milestone_due', 'Jalon à échéance'), ('meeting_reminder', 'Rappel de réunion'), ('meeting_started', 'Réunion démarrée'), ('meeting_completed', 'Réunion terminée'), ('project_created', 'Projet créé'), ('meeting_processing', 'Traitement de réunion en cours'), ('meeting_processed', "Réunion traitée par l'IA"), ('report_processing', 'Génération de rapport en cours'), ('report_ready', 'Rapport de projet prêt'), ('task_failed', "Échec d'une tâche en arrière-plan")], max_length=30),
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=80)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_events',
                'indexes': [models.Index(fields=['service', '-processed_at'], name='processed_e_service_2c2e63_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='processedevent',
            constraint=models.UniqueConstraint(fields=('service', 'event_id'), name='unique_service_event'),
        ),
        migrations.AddField(
            model_name='eventoutbox',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoutbox',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_outbox', to='api.company'),
        ),
        migrations.AddField(
            model_name='eventmetric',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_metrics', to='api.company'),
        ),
        migrations.AddField(
            model_name='eventauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_audit_logs', to='api.company'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['status', 'created_at'], name='event_outbo_status_bd9755_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['event_type', 'created_at'], name='event_outbo_event_t_d2914c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['company', 'created_at'], name='event_outbo_company_8e60f3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmetric',
            index=models.Index(fields=['date', 'event_type'], name='event_metri_date_5cd46e_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmetric',
            constraint=models.UniqueConstraint(fields=('tenant_key', 'event_type', 'date'), name='unique_tenant_event_metric'),
        ),
        migrations.AddIndex(
            model_name='eventauditlog',
            index=models.Index(fields=['event_type', '-occurred_at'], name='event_audit_event_t_0495c6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventauditlog',
            index=models.Index(fields=['company', '-occurred_at'], name='event_audit_company_0af922_idx'),
        ),
        migrations.AddIndex(
            model_name='eventauditlog',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='event_audit_aggrega_62cf60_idx'),
        ),
    ]
