# Generated by Django 4.2.7 on 2026-07-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meeting_reminder_sent_at_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=150)),
                ('source_service', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(help_text="Horodatage d'émission de l'événement (côté producteur)")),
                ('consumed_at', models.DateTimeField(auto_now_add=True, help_text='Horodatage de consommation (côté audit)')),
            ],
            options={
                'verbose_name': "Événement d'audit",
                'verbose_name_plural': "Événements d'audit",
                'db_table': 'audit_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', '-occurred_at'], name='audit_event_event_t_39c42d_idx'), models.Index(fields=['topic', '-occurred_at'], name='audit_event_topic_572289_idx')],
            },
        ),
    ]
