# Generated by Django 4.2.7 on 2026-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventauditlog_eventmetric_eventoutbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoutbox',
            name='actor_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoutbox',
            name='company_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
