# Generated by Django 4.2.7 on 2026-07-26 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_0008_auditevent_0009_event_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=20)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost_per_diem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_accommodation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expense_report', models.TextField(blank=True, default='')),
                ('mission_report', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission Member',
                'verbose_name_plural': 'Mission Members',
                'db_table': 'mission_members',
                'indexes': [models.Index(fields=['mission', 'is_leader'], name='mission_mem_mission_65c1b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='missionmember',
            constraint=models.UniqueConstraint(fields=('mission', 'user'), name='unique_mission_member'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status'], name='missions_status_e455e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['company', 'status'], name='missions_company_722264_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['start_date'], name='missions_start_d_8ae318_idx'),
        ),
    ]
