# Generated by Django 4.2.7 on 2026-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mission_missionmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='currency',
            field=models.CharField(blank=True, default='xof', max_length=10),
        ),
    ]
