# Generated by Django 4.2.7 on 2026-07-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mission_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='missions', to='api.milestone'),
        ),
        migrations.AddField(
            model_name='mission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.project'),
        ),
        migrations.AddField(
            model_name='mission',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='missions', to='api.task'),
        ),
    ]
