# Generated by Django 4.2.7 on 2026-08-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mission_link_project_tasks_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['meeting', 'created_at'], name='meeting_cha_meeting_30a0fd_idx')],
            },
        ),
    ]
