# Generated by Django 4.2.7 on 2026-08-03 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meetingchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.meeting'),
        ),
        migrations.AddField(
            model_name='meetingchatmessage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='api.file'),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
