# Generated by Django 4.2.7 on 2026-08-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_file_category_file_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
