# Generated by Django 4.2.7 on 2026-09-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_parc_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicule',
            field=models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV / 4x4'), ('pickup', 'Pick-up'), ('utilitaire', 'Utilitaire'), ('camion', 'Camion'), ('moto', 'Moto'), ('autre', 'Autre')], default='berline', max_length=20),
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_photos_uploaded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Photo véhicule',
                'verbose_name_plural': 'Photos véhicules',
                'db_table': 'vehicle_photos',
                'ordering': ['created_at'],
            },
        ),
    ]
