# Generated by Django 4.2.7 on 2026-09-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('avion', 'Avion'), ('vehicule_personnel', 'Véhicule personnel'), ('vehicule_parc', 'Véhicule du parc'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('train', 'Train'), ('bateau', 'Bateau'), ('autre', 'Autre')], default='taxi', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_transports', to='api.company')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='api.mission')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_transports', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Transport de mission',
                'verbose_name_plural': 'Transports de mission',
                'db_table': 'mission_transports',
                'ordering': ['id'],
            },
        ),
    ]
